# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-17 09:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=1000)),
                ('image_id', models.CharField(max_length=300)),
                ('container_id', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_id', models.CharField(default='', max_length=100)),
                ('network_name', models.CharField(max_length=300)),
                ('network_id', models.CharField(max_length=300)),
                ('mac_address', models.CharField(max_length=17)),
                ('ip_address', models.CharField(max_length=40)),
                ('gateway_address', models.CharField(blank=True, max_length=40)),
                ('subnet_prefix_length', models.IntegerField(default=0)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='containerstorage.Container')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_uuid', models.CharField(default='', max_length=100)),
                ('host_name', models.CharField(blank=True, max_length=1000)),
                ('docker_version', models.CharField(blank=True, max_length=15)),
                ('last_updated', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='container',
            name='host_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='containerstorage.Node'),
        ),
    ]
