# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-18 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containerstorage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='container',
            name='service',
            field=models.ForeignKey(blank=True, null=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='containerstorage.Service'),
        ),
    ]
