# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-14 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containerstorage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='engine_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
