# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-14 13:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containerstorage', '0002_node_engine_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='docker_version',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='node',
            name='host_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='node',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
