# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-20 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containerstorage', '0003_container_service_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkInterfaceNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_id', models.CharField(default='', max_length=100)),
                ('network_name', models.CharField(max_length=300)),
                ('network_id', models.CharField(max_length=300)),
                ('mac_address', models.CharField(max_length=17)),
                ('ip_address', models.CharField(max_length=40)),
                ('gateway_address', models.CharField(blank=True, max_length=40, null=True)),
                ('subnet_prefix_length', models.IntegerField(default=0)),
                ('ip6_address', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='container',
            name='host_name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='networkinterface',
            name='gateway_address',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='networkinterfacenode',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='containerstorage.Container'),
        ),
    ]
